### ISSUE TITLE
Create a custom cmake function for compiling the components

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-controllers#24]
Every time a new component is added the very similar `CMakeLists.txt` has to be copied from one component to the other (i.e. [here](https://github.com/dic-iit/bipedal-locomotion-controllers/blob/e26ec3444e7837f17b3cdd0156ed15690ff08496/src/Estimators/CMakeLists.txt) or [here](https://github.com/dic-iit/bipedal-locomotion-controllers/blob/master/src/ParametersHandler/CMakeLists.txt)). I really don't like this copy-paste of code because it may lead to errors.   
I think that it could be a nice idea to implement a `CMake` function similar to the one written by @S-Dafarra for the [`unit tests` ](https://github.com/dic-iit/bipedal-locomotion-controllers/blob/master/cmake/AddBipedalLocomotionControllersUnitTest.cmake).

cc @traversaro

**Comment by S-Dafarra** [comment]
I agree. I guess that the main difference would be between libraries and executables, but this may be an option to a hypothetic function.

**Comment by traversaro** [comment]
I think it is a good idea. The amount of duplicate boilerplate CMake code for each library is indeed risky and prone to errors. We did something similar in gazebo-yarp-plugins, and the only reason we did not do that for https://github.com/robotology/how-to-export-cpp-library is that it would complexify readability for a tutorial such as that..

**Comment by traversaro** [comment]
Interesting takes on "we need to reduce the complexity and variability of C++ libraries build system": 
* https://vector-of-bool.github.io/2020/01/06/new-decade.html
* https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs
