### ISSUE TITLE
Rename the repository and the Namespaces

### ISSUE THREAD

**Issue by GiulioRomualdi** [dic-iit/bipedal-locomotion-controllers#38]
Discussing with @S-Dafarra we were thinking to rename the repository and the namespaces.

One of the possible solutions is to rename the repo in `bipedal-locomotion-framework` and change the `namespace` from `BipedalLocomotionController` to `BLF`. 

@traversaro @MiladShafiee  any idea?

**Comment by traversaro** [comment]
Ok for me.

**Comment by S-Dafarra** [comment]
What about renaming the namespace in ``BipedalLocomotion``. Then we could have, ``BipedalLocomotion::Controllers``, ``BipedalLocomotion::Planners``, ``BipedalLocomotion::Utilities``... Maybe it is a bit long, but probably it is already late for that :grin:
